# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Rose
email: benjamin.rose@me.com
description: > # this means to ignore newlines until "baseurl:"
  A little corner of the Internet for me. A place to share my thoughts
  about technology, science, and education.
baseurl: "" # the subpath of your site, e.g. /blog, adds everypage after this
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _benjaminrose
github_username:  benjaminrose
# flikr_username: 

# Build settings
markdown: kramdown

## blog settings
permalink: /blog/:year/:month/:day/:title.html
##Peronal gems and additions
# add files that Jekyll wants to ignore
include: []
#allow future posts to wait to be deployed, https://talk.jekyllrb.com/t/latest-posts-not-being-output-in-for-loop/2006/2?u=anthonyjsmith
#this posts them NOW, not later!
# future: true

#jekyll-archives does things by year and stores the categories strangly. 
# it was easier to just make my own pages.

gems:
  - jekyll-paginate

##index page!
paginate: 7
paginate_path: "page:num"